### ISSUE TITLE
Nice work with your version of stevenson.space

### ISSUE THREAD

**Issue by josephshepin** [VoxelPrismatic/aeshs.sp#1]
Hi, It's Joseph from [stevenson.space](https://stevenson.space). Nice job making your own version of the site - it's pretty cool. You are always free to contribute to the production version if you like! - Joseph

**Comment by VoxelPrismatic** [comment]
Actually I started this project because stevenson.space didn't work on my ipad up until this year. Now I prefer it since it loads instantly

~ Daniel
________________________________
From: Joseph Shepin ***@***.***>
Sent: Monday, April 18, 2022 11:02:16 PM
To: VoxelPrismatic/aeshs.sp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VoxelPrismatic/aeshs.sp] Nice work with your version of stevenson.space (Issue #1)


Hi, It's Joseph from stevenson.space<https://stevenson.space>. Nice job making your own version of the site - it's pretty cool. You are always free to contribute to the production version if you like! - Joseph

**Comment by josephshepin** [comment]
huh. it's weird that it didn't work on your ipad - are you using an off-brand browser? What about it didn't work?

**Comment by VoxelPrismatic** [comment]
it works now, i think i enabled a developer option pre-iPadOS and it broke the timer. however, the timer did work in the colors page, which is very curious.

~ Daniel
________________________________

**Comment by VoxelPrismatic** [comment]
moreover it wouldn't change anything since all iOS browsers are safari with a skin

~ Daniel
________________________________

**Comment by josephshepin** [comment]
that seems to be an isolated issue that may have been fixed on Apple's end as we didn't update anything about the timer in a long time.

**Comment by VoxelPrismatic** [comment]
yup. but thats how this originated, and i still love how light my version is compared to the original. mine doesn't look as great, but if i don't need to know the menu, future events, etc, ill take my instant load time instead.

maybe ill contribute a 'quick' loader under stevenson.space/quick which is essentially mine, without the links to me.
________________________________

**Comment by josephshepin** [comment]
yeah, calling in the vanilla JS assets is always going to be faster. i'm not sure /quick would be any faster as it would require vue.

**Comment by VoxelPrismatic** [comment]
i see
________________________________

**Comment by JosephShepin** [comment]
It would be possible to have domain level switch like fast.stevenson.space. But the .3 second difference it would make is negated by the time it takes to type the extra word "fast".
